create_new_adapter: true
cutoff_len: 256
dataset: lunyu_sample
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_thinking: false
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 2
include_num_input_tokens_seen: true
learning_rate: 0.0001
logging_steps: 1
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: Qwen/Qwen2.5-0.5B
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves\Qwen2.5-0.5B\lora\train_2026-09-02-10-24-13
packing: false
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 10
stage: sft
template: qwen
trust_remote_code: true
warmup_steps: 0
